<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5d515e9865bee',
	'title' => 'Page Option',
	'fields' => array(
		array(
			'key' => 'field_5d515ed21d146',
			'label' => 'Description',
			'name' => '_description',
			'type' => 'text',
			'instructions' => 'Enter your page description.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5d515ee61d147',
			'label' => 'Layout',
			'name' => 'layout',
			'type' => 'select',
			'instructions' => 'Select page content and sidebar alignment.	
Default is configured in Theme Options - Page Options.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Default' => 'Default',
				'Full Width' => 'Full Width',
				'Left Sidebar' => 'Left Sidebar',
				'Right Sidebar' => 'Right Sidebar',
			),
			'default_value' => array(
				0 => 'Default',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5d515f281d148',
			'label' => 'Sidebar',
			'name' => 'sidebar',
			'type' => 'select',
			'instructions' => 'Select page sidebar.	
Default is configured in Theme Options - Page Options.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Default' => 'Default',
				'Full Width' => 'Full Width',
				'Left Sidebar' => 'Left Sidebar',
				'Right Sidebar' => 'Right Sidebar',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5d517073bcf3a',
			'label' => 'Sidebar Style',
			'name' => 'sidebar',
			'type' => 'select',
			'instructions' => 'Select sidebar style.	
Default is configured in Theme Options - Page Options.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Default' => 'Default',
				'Simple' => 'Simple',
				'Box' => 'Box',
			),
			'default_value' => array(
				0 => 'Default',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5d5170adbcf3b',
			'label' => 'Fixed Sidebar',
			'name' => 'fixed_sidebar',
			'type' => 'checkbox',
			'instructions' => 'If selected, the sidebar will be fixed.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Fixed Sidebar' => 'Fixed Sidebar',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5d5170c5bcf3c',
			'label' => 'Secondary Menu',
			'name' => 'secondary_menu',
			'type' => 'select',
			'instructions' => 'Default
Primary Menu
Header Menu
Secondary Menu',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5d52508a30e0a',
			'label' => 'Main Navigation Menu',
			'name' => 'main_navigation_menu',
			'type' => 'select',
			'instructions' => 'Default
Primary Menu
Header Menu
Secondary Menu',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Default' => 'Default',
				'Primary Menu' => 'Primary Menu',
				'Header Menu' => 'Header Menu',
				'Secondary Menu' => 'Secondary Menu',
			),
			'default_value' => array(
				0 => 'Default',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5d5250d330e0b',
			'label' => 'Disable Sticky Header',
			'name' => 'disable_sticky_header',
			'type' => 'checkbox',
			'instructions' => 'If selected, the sticky header will be disabled.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Disable Sticky Header' => 'Disable Sticky Header',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5d52512d30e0c',
			'label' => 'Disable Logo',
			'name' => 'disable_logo',
			'type' => 'checkbox',
			'instructions' => 'If selected, logo will be hidden.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Disable Logo' => 'Disable Logo',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5d52514930e0d',
			'label' => 'Disable Main Menu',
			'name' => 'disable_main_menu',
			'type' => 'checkbox',
			'instructions' => 'If selected, the main menu will be hidden.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Disable Main Menu' => 'Disable Main Menu',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5d52518230e0e',
			'label' => 'Disable Main Menu Items',
			'name' => 'disable_main_menu_items',
			'type' => 'checkbox',
			'instructions' => 'If selected, main menu items will be hidden.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Disable Main Menu Items' => 'Disable Main Menu Items',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5d5251c830e0f',
			'label' => 'Disable Title/Description',
			'name' => 'disable_titledescription',
			'type' => 'checkbox',
			'instructions' => 'If selected, title and decription will be hidden.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5d5251e830e10',
			'label' => 'Disable Top Bar',
			'name' => 'disable_top_bar',
			'type' => 'checkbox',
			'instructions' => 'If selected, top bar will be hidden.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Disable Top Bar' => 'Disable Top Bar',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5d52521730e11',
			'label' => 'Disable Content Area',
			'name' => 'disable_content_area',
			'type' => 'checkbox',
			'instructions' => 'If selected, the content area will be hidden (including sidebar and comments).',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Disable Content Area' => 'Disable Content Area',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5d52523530e12',
			'label' => 'Disable Smart Button',
			'name' => 'disable_smart_button',
			'type' => 'checkbox',
			'instructions' => 'If selected, Smart Button Side Area will be hidden.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Disable Smart Button' => 'Disable Smart Button',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5d52527930e13',
			'label' => 'Disable Footer Widgets',
			'name' => 'disable_footer_widgets',
			'type' => 'checkbox',
			'instructions' => 'If selected, footer widgets will be hidden.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Disable Footer Widgets' => 'Disable Footer Widgets',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5d5252ac30e14',
			'label' => 'Disable Footer Copyright',
			'name' => 'disable_footer_copyright',
			'type' => 'checkbox',
			'instructions' => 'If selected, footer copyright area will be hidden.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5da19bd060e33',
	'title' => 'Post Option',
	'fields' => array(
		array(
			'key' => 'field_5da19bd094fe6',
			'label' => 'Description',
			'name' => '_description',
			'type' => 'text',
			'instructions' => 'Enter your page description.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5da19bd095020',
			'label' => 'Layout',
			'name' => 'layout',
			'type' => 'select',
			'instructions' => 'Select page content and sidebar alignment.	
Default is configured in Theme Options - Page Options.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Default' => 'Default',
				'Full Width' => 'Full Width',
				'Left Sidebar' => 'Left Sidebar',
				'Right Sidebar' => 'Right Sidebar',
			),
			'default_value' => array(
				0 => 'Default',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5da19bd095057',
			'label' => 'Sidebar',
			'name' => 'sidebar',
			'type' => 'select',
			'instructions' => 'Select page sidebar.	
Default is configured in Theme Options - Page Options.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Default' => 'Default',
				'Full Width' => 'Full Width',
				'Left Sidebar' => 'Left Sidebar',
				'Right Sidebar' => 'Right Sidebar',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5da19bd09508e',
			'label' => 'Sidebar Style',
			'name' => 'sidebar',
			'type' => 'select',
			'instructions' => 'Select sidebar style.	
Default is configured in Theme Options - Page Options.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Default' => 'Default',
				'Simple' => 'Simple',
				'Box' => 'Box',
			),
			'default_value' => array(
				0 => 'Default',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5da19bd0950c6',
			'label' => 'Fixed Sidebar',
			'name' => 'fixed_sidebar',
			'type' => 'checkbox',
			'instructions' => 'If selected, the sidebar will be fixed.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Fixed Sidebar' => 'Fixed Sidebar',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5da19bd0950fd',
			'label' => 'Secondary Menu',
			'name' => 'secondary_menu',
			'type' => 'select',
			'instructions' => 'Default
Primary Menu
Header Menu
Secondary Menu',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5da19bd095134',
			'label' => 'Main Navigation Menu',
			'name' => 'main_navigation_menu',
			'type' => 'select',
			'instructions' => 'Default
Primary Menu
Header Menu
Secondary Menu',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Default' => 'Default',
				'Primary Menu' => 'Primary Menu',
				'Header Menu' => 'Header Menu',
				'Secondary Menu' => 'Secondary Menu',
			),
			'default_value' => array(
				0 => 'Default',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5da19bd09516c',
			'label' => 'Disable Sticky Header',
			'name' => 'disable_sticky_header',
			'type' => 'checkbox',
			'instructions' => 'If selected, the sticky header will be disabled.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Disable Sticky Header' => 'Disable Sticky Header',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5da19bd0951a3',
			'label' => 'Disable Logo',
			'name' => 'disable_logo',
			'type' => 'checkbox',
			'instructions' => 'If selected, logo will be hidden.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Disable Logo' => 'Disable Logo',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5da19bd0951da',
			'label' => 'Disable Main Menu',
			'name' => 'disable_main_menu',
			'type' => 'checkbox',
			'instructions' => 'If selected, the main menu will be hidden.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Disable Main Menu' => 'Disable Main Menu',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5da19bd095212',
			'label' => 'Disable Main Menu Items',
			'name' => 'disable_main_menu_items',
			'type' => 'checkbox',
			'instructions' => 'If selected, main menu items will be hidden.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Disable Main Menu Items' => 'Disable Main Menu Items',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5da19bd095249',
			'label' => 'Disable Title/Description',
			'name' => 'disable_titledescription',
			'type' => 'checkbox',
			'instructions' => 'If selected, title and decription will be hidden.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5da19bd095280',
			'label' => 'Disable Top Bar',
			'name' => 'disable_top_bar',
			'type' => 'checkbox',
			'instructions' => 'If selected, top bar will be hidden.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Disable Top Bar' => 'Disable Top Bar',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5da19bd0952b7',
			'label' => 'Disable Content Area',
			'name' => 'disable_content_area',
			'type' => 'checkbox',
			'instructions' => 'If selected, the content area will be hidden (including sidebar and comments).',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Disable Content Area' => 'Disable Content Area',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5da19bd0952ee',
			'label' => 'Disable Smart Button',
			'name' => 'disable_smart_button',
			'type' => 'checkbox',
			'instructions' => 'If selected, Smart Button Side Area will be hidden.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Disable Smart Button' => 'Disable Smart Button',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5da19bd095325',
			'label' => 'Disable Footer Widgets',
			'name' => 'disable_footer_widgets',
			'type' => 'checkbox',
			'instructions' => 'If selected, footer widgets will be hidden.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Disable Footer Widgets' => 'Disable Footer Widgets',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5da19bd09535c',
			'label' => 'Disable Footer Copyright',
			'name' => 'disable_footer_copyright',
			'type' => 'checkbox',
			'instructions' => 'If selected, footer copyright area will be hidden.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5d52536a03efe',
	'title' => 'Feature Section',
	'fields' => array(
		array(
			'key' => 'field_5d52538dbded1',
			'label' => 'Feature Element',
			'name' => 'feature_element',
			'type' => 'select',
			'instructions' => 'Select the feature section element.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'None' => 'None',
				'Title' => 'Title',
				'Image' => 'Image',
				'Video' => 'Video',
				'Slider' => 'Slider',
				'Map' => 'Map',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5d5253e2bded2',
			'label' => 'Select Slider',
			'name' => 'select_slider',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5d52538dbded1',
						'operator' => '==',
						'value' => 'Slider',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'None' => 'None',
				'Revolution Slider 1' => 'Revolution Slider 1',
				'Revolution Slider 2' => 'Revolution Slider 2',
				'Revolution Slider 3' => 'Revolution Slider 3',
			),
			'default_value' => array(
				0 => 'None',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5d525444bded3',
			'label' => 'Feature Size',
			'name' => 'feature_size',
			'type' => 'select',
			'instructions' => 'With Custom Size option you can select the feature height.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Full Screen' => 'Full Screen',
				'Custom Size' => 'Custom Size',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5d525583e84e9',
			'label' => 'Height',
			'name' => 'height',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5d525444bded3',
						'operator' => '==',
						'value' => 'Custom Size',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 300,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'PX',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5d525629abc9a',
			'label' => 'Feature/Header Position',
			'name' => 'featureheader_position',
			'type' => 'select',
			'instructions' => 'With this option, header will be shown above or below feature section.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Header above Feature' => 'Header above Feature',
				'Header below Feature' => 'Header below Feature',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5d5257def477b',
			'label' => 'Header Integration',
			'name' => 'header_integration',
			'type' => 'radio',
			'instructions' => 'With this option feature section will be integrated into the header.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Yes' => 'Yes',
				'No' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'No',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5d52584bbd58e',
			'label' => 'Header Style',
			'name' => 'header_style',
			'type' => 'select',
			'instructions' => 'With this option, you can change the coloring of your header.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Default' => 'Default',
				'Dark' => 'Dark',
				'Light' => 'Light',
			),
			'default_value' => array(
				0 => 'Default',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5d525889bd58f',
			'label' => 'Enable Parallax Effect',
			'name' => 'enable_parallax_effect',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Enable Parallax Effect' => 'Enable Parallax Effect',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'horizontal',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5d525932d51b1',
			'label' => 'Enable Bottom Arrow',
			'name' => 'enable_bottom_arrow',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Enable Bottom Arrow' => 'Enable Bottom Arrow',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'horizontal',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5d70e2682349e',
			'label' => 'Title',
			'name' => 'title',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5d52538dbded1',
						'operator' => '==',
						'value' => 'Title',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d70e55e2349f',
					'label' => 'Title',
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d70e569234a0',
					'label' => 'Caption',
					'name' => 'caption',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d70e573234a1',
					'label' => 'Title Color',
					'name' => 'title_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#000000',
				),
				array(
					'key' => 'field_5d70e57d234a2',
					'label' => 'Caption Color',
					'name' => 'caption_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#000000',
				),
				array(
					'key' => 'field_5d70e5f5234a3',
					'label' => 'Title Tag',
					'name' => 'title_tag',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'div' => 'div',
						'h1' => 'h1',
						'h2' => 'h2',
						'h3' => 'h3',
						'h4' => 'h4',
						'h5' => 'h5',
						'h6' => 'h6',
					),
					'default_value' => array(
						0 => 'h1',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70e63d234a4',
					'label' => 'Caption Tag',
					'name' => 'caption_tag',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'div' => 'div',
						'h1' => 'h1',
						'h2' => 'h2',
						'h3' => 'h3',
						'h4' => 'h4',
						'h5' => 'h5',
						'h6' => 'h6',
					),
					'default_value' => array(
						0 => 'div',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70e676234a5',
					'label' => 'Background Color',
					'name' => 'background_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#465412',
				),
				array(
					'key' => 'field_5d70e69d234a6',
					'label' => 'Alignment',
					'name' => 'alignment',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'left' => 'left',
						'center' => 'center',
						'right' => 'right',
					),
					'default_value' => array(
						0 => 'Center',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70e795234a7',
					'label' => 'Extra Class',
					'name' => 'extra_class',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5d70e7c41e5f7',
			'label' => 'Image',
			'name' => 'image',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5d52538dbded1',
						'operator' => '==',
						'value' => 'Image',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'field_5d70e7f71e5f8',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5d70e81a1e5f9',
					'label' => 'Title',
					'name' => 'title_image',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d70e8d41e5fa',
					'label' => 'Caption',
					'name' => 'image_caption',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d70e8e51e5fb',
					'label' => 'Title Color',
					'name' => 'title_color_image',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5d70e99a1e5fc',
					'label' => 'Caption Color',
					'name' => 'caption_color_image',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5d70e9b51e5fd',
					'label' => 'Title Tag',
					'name' => 'title_tag_image',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'div' => 'div',
						'h1' => 'h1',
						'h2' => 'h2',
						'h3' => 'h3',
						'h4' => 'h4',
						'h5' => 'h5',
						'h6' => 'h6',
					),
					'default_value' => array(
						0 => 'H1',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70e9d71e5fe',
					'label' => 'Caption Tag',
					'name' => 'caption_tag_image',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'div' => 'div',
						'h1' => 'h1',
						'h2' => 'h2',
						'h3' => 'h3',
						'h4' => 'h4',
						'h5' => 'h5',
						'h6' => 'h6',
					),
					'default_value' => array(
						0 => 'div',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70ea9a1e5ff',
					'label' => 'Alignment',
					'name' => 'alignment_image',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'left' => 'left',
						'center' => 'center',
						'right' => 'right',
					),
					'default_value' => array(
						0 => 'center',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70eb4121300',
					'label' => 'Image Background Position',
					'name' => 'background_position_image',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Left Top' => 'Left Top',
						'Left Center' => 'Left Center',
						'Left Bottom' => 'Left Bottom',
						'Center Top' => 'Center Top',
						'Center Center' => 'Center Center',
						'Center Bottom' => 'Center Bottom',
						'Right Top' => 'Right Top',
						'Right Center' => 'Right Center',
						'Right Bottom' => 'Right Bottom',
					),
					'default_value' => array(
						0 => 'Center Center',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70efcf21301',
					'label' => 'Pattern Overlay',
					'name' => 'overlay_image',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Yes' => 'Yes',
						'No' => 'No',
					),
					'default_value' => array(
						0 => 'No',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70f03621302',
					'label' => 'Color Overlay',
					'name' => 'color_overlay_image',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'None' => 'None',
						'dark' => 'dark',
						'light' => 'light',
						'primary-1' => 'primary-1',
						'primary-2' => 'primary-2',
						'primary-3' => 'primary-3',
						'primary-4' => 'primary-4',
						'primary-5' => 'primary-5',
					),
					'default_value' => array(
						0 => 'None',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70f0f021303',
					'label' => 'Opacity Overlay',
					'name' => 'opacity_overlay_image',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						10 => '10',
						20 => '20',
						30 => '30',
						40 => '40',
						50 => '50',
						'60:' => '60:',
						70 => '70',
						80 => '80',
						90 => '90',
						100 => '100',
					),
					'default_value' => array(
						0 => 10,
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70f1ae21304',
					'label' => 'First Button Text',
					'name' => 'first_button_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d70f22a21305',
					'label' => 'Button URL',
					'name' => 'first_button_url_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d70f27221306',
					'label' => 'Button Target',
					'name' => 'button_target',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Same Page' => 'Same Page',
						'New Page' => 'New Page',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70f2ed21307',
					'label' => 'Button Color',
					'name' => 'button_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5d70f33621308',
					'label' => 'Button Class',
					'name' => 'button_class',
					'type' => 'text',
					'instructions' => 'example: kandy_btn_square	kandy_btn_round	kandy_btn_extra_round
You can add the custom class.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'kandy_btn_square',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d70f43c21309',
					'label' => 'Second ButtonText',
					'name' => 'second_button_text_image',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d70f4732130a',
					'label' => 'Button URL',
					'name' => 'second_button_url_image',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d70f4922130b',
					'label' => 'Button Target',
					'name' => 'second_button_target_image',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Same Page' => 'Same Page',
						'New Page' => 'New Page',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70f4af2130c',
					'label' => 'Button Color',
					'name' => 'second_button_color_image',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5d70f4c92130d',
					'label' => 'Button Class',
					'name' => 'second_button_class_image',
					'type' => 'text',
					'instructions' => 'example: kandy_btn_square	kandy_btn_round	kandy_btn_extra_round
You can add the custom class.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'kandy_btn_square',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5d70f649548e2',
			'label' => 'Feature Video',
			'name' => 'feature_video',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5d52538dbded1',
						'operator' => '==',
						'value' => 'Video',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'field_5d70f65e548e3',
					'label' => 'WebM File URL',
					'name' => 'video_webm_file_url',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '.webm',
				),
				array(
					'key' => 'field_5d70f71b548e4',
					'label' => 'MP4 File URL',
					'name' => 'video_mp4_file_url',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '.mp4',
				),
				array(
					'key' => 'field_5d70f73e548e5',
					'label' => 'OGV File URL',
					'name' => 'videp_ogv_file_url',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '.ogv',
				),
				array(
					'key' => 'field_5d70f75e548e6',
					'label' => 'Fallback Image',
					'name' => 'fallback_image',
					'type' => 'image',
					'instructions' => 'Use same resolution as video.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5d70f7d5548e7',
					'label' => 'Use Fallback Image as Poster',
					'name' => 'use_fallback_image_as_poster',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Yes' => 'Yes',
						'No' => 'No',
					),
					'default_value' => array(
						0 => 'Yes',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70f7f5548e8',
					'label' => 'Video Loop',
					'name' => 'video_loop',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Yes' => 'Yes',
						'No' => 'No',
					),
					'default_value' => array(
						0 => 'Yes',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70f80b548e9',
					'label' => 'Muted',
					'name' => 'muted',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Yes' => 'Yes',
						'No' => 'No',
					),
					'default_value' => array(
						0 => 'Yes',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70fc4b8aaed',
					'label' => 'Title',
					'name' => 'title_video',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d70fc1f8aaec',
					'label' => 'Caption',
					'name' => 'video_caption',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d70fbd78aae9',
					'label' => 'Title Color',
					'name' => 'title_color_video',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5d70fbc38aae8',
					'label' => 'Caption Color',
					'name' => 'caption_color_video',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5d70fbb08aae7',
					'label' => 'Title Tag',
					'name' => 'title_tag_video',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'div' => 'div',
						'h1' => 'h1',
						'h2' => 'h2',
						'h3' => 'h3',
						'h4' => 'h4',
						'h5' => 'h5',
						'h6' => 'h6',
					),
					'default_value' => array(
						0 => 'H1',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70fba08aae6',
					'label' => 'Caption Tag',
					'name' => 'caption_tag_video',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'div' => 'div',
						'h1' => 'h1',
						'h2' => 'h2',
						'h3' => 'h3',
						'h4' => 'h4',
						'h5' => 'h5',
						'h6' => 'h6',
					),
					'default_value' => array(
						0 => 'div',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70fb8a8aae5',
					'label' => 'Alignment',
					'name' => 'alignment_video_text',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'left' => 'left',
						'center' => 'center',
						'right' => 'right',
					),
					'default_value' => array(
						0 => 'center',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70fb5d8aae4',
					'label' => 'Pattern Overlay',
					'name' => 'overlay_image_video',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Yes' => 'Yes',
						'No' => 'No',
					),
					'default_value' => array(
						0 => 'No',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70fb468aae3',
					'label' => 'Color Overlay',
					'name' => 'color_overlay_video',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'None' => 'None',
						'dark' => 'dark',
						'light' => 'light',
						'primary-1' => 'primary-1',
						'primary-2' => 'primary-2',
						'primary-3' => 'primary-3',
						'primary-4' => 'primary-4',
						'primary-5' => 'primary-5',
					),
					'default_value' => array(
						0 => 'None',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70fb358aae2',
					'label' => 'Opacity Overlay',
					'name' => 'opacity_overlay_video',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						10 => '10',
						20 => '20',
						30 => '30',
						40 => '40',
						50 => '50',
						'60:' => '60:',
						70 => '70',
						80 => '80',
						90 => '90',
						100 => '100',
					),
					'default_value' => array(
						0 => 10,
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70fac88aae1',
					'label' => 'First Button Text',
					'name' => 'first_button_text_video',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d70faac8aae0',
					'label' => 'Button URL',
					'name' => 'first_button_url_text_video',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d70fa9a8aadf',
					'label' => 'Button Target',
					'name' => 'button_target_video',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Same Page' => 'Same Page',
						'New Page' => 'New Page',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70fa898aade',
					'label' => 'Button Color',
					'name' => 'button_color_video',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5d70fa6f8aadd',
					'label' => 'Button Class',
					'name' => 'button_class_video',
					'type' => 'text',
					'instructions' => 'example: kandy_btn_square	kandy_btn_round	kandy_btn_extra_round
You can add the custom class.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'kandy_btn_square',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d70f9ce8aadc',
					'label' => 'Second ButtonText',
					'name' => 'second_button_text_video',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d70f9af8aadb',
					'label' => 'Button URL',
					'name' => 'second_button_url_video',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d70f99e8aada',
					'label' => 'Button Target',
					'name' => 'second_button_target_video',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Same Page' => 'Same Page',
						'New Page' => 'New Page',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d70f9888aad9',
					'label' => 'Button Color',
					'name' => 'second_button_color_video',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5d70f9728aad8',
					'label' => 'Button Class',
					'name' => 'second_button_class_video',
					'type' => 'text',
					'instructions' => 'example: kandy_btn_square	kandy_btn_round	kandy_btn_extra_round
You can add the custom class.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'kandy_btn_square',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif; 
?>